name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    name: Generate Purple Contribution Snake
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Ayantika2006
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            dist/github-snake.svg?color_snake=9D4EDD&color_dots=#0d001a,#3a0080,#6600cc,#9D4EDD,#C77DFF
            dist/github-snake-dark.svg?color_snake=C77DFF&color_dots=#0d001a,#3a0080,#6600cc,#9D4EDD,#C77DFF

      - name: Publish Snake
        uses: crazy-max/ghaction-github-pages@v3
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
